# Generated by Django 5.0.6 on 2024-05-28 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='From',
            field=models.CharField(default='Hello', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='email',
            name='To',
            field=models.CharField(default='Hello', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='email',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='high', max_length=10),
        ),
    ]
